/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 100
#define YY_END_OF_BUFFER 101
static yyconst short int yy_acclist[425] =
    {   0,
      101,   99,  100,   98,   99,  100,   98,  100,   86,   99,
      100,   99,  100,   92,   99,  100,   85,   99,  100,   99,
      100,   80,   99,  100,   81,   99,  100,   90,   99,  100,
       89,   99,  100,   77,   99,  100,   88,   99,  100,   84,
       99,  100,   91,   99,  100,   42,   99,  100,   43,   99,
      100,   78,   99,  100,   74,   99,  100,   93,   99,  100,
       79,   99,  100,   94,   99,  100,   97,   99,  100,   40,
       99,  100,   40,   99,  100,   82,   99,  100,   83,   99,
      100,   95,   99,  100,   40,   99,  100,   40,   99,  100,
       40,   99,  100,   40,   99,  100,   40,   99,  100,   40,

       99,  100,   40,   99,  100,   40,   99,  100,   40,   99,
      100,   40,   99,  100,   40,   99,  100,   40,   99,  100,
       40,   99,  100,   40,   99,  100,   40,   99,  100,   40,
       99,  100,   75,   99,  100,   96,   99,  100,   76,   99,
      100,   87,   99,  100,   73,   51,   59,   76,   68,   60,
       57,   65,   55,   66,   56,   67,   46,    1,    2,   58,
       47,   42,   42,   42,   42,   43,   43,   43,   43,   83,
       75,   82,   64,   70,   72,   71,   63,   40,   61,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   12,   40,
       40,   40,   40,   40,   40,   40,   20,   40,   40,   40,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   62,
       69,   44,   52,   46,    2,   46,   47,   47,   45,   42,
       42,   42,   42,   41,   43,   43,   43,   43,   54,   53,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   18,   40,   40,   40,   23,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   46,   46,   47,   47,
       45,   42,   49,   50,   41,   41,   41,   43,   40,   40,
       40,    3,   40,   40,    6,   40,    7,   40,   40,   40,
       40,   40,   14,   40,   15,   40,   40,   40,   19,   40,

       40,   24,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   37,   40,   40,   40,   46,
       47,   49,   49,   50,   50,   41,   41,   48,   41,   41,
        4,   40,   40,   40,    5,   40,    9,   40,   40,   40,
       40,   40,   17,   40,   40,   40,   40,   40,   28,   40,
       40,   40,   40,   40,   40,   40,   35,   40,   40,   40,
       39,   40,   49,   49,   50,   50,   48,   41,   40,   40,
       40,   40,   13,   40,   16,   40,   22,   40,   40,   40,
       27,   40,   29,   40,   30,   40,   31,   40,   32,   40,
       33,   40,   40,   40,   40,   49,   50,   40,   40,   40,

       11,   40,   40,   40,   34,   40,   40,   40,    8,   40,
       40,   10,   40,   25,   40,   26,   40,   36,   40,   38,
       40,   40,   21,   40
    } ;

static yyconst short int yy_accept[318] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   52,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  136,
      139,  142,  145,  146,  146,  147,  147,  148,  149,  150,
      151,  151,  151,  152,  153,  154,  155,  156,  157,  157,
      158,  159,  160,  161,  162,  163,  163,  163,  164,  165,
      165,  166,  167,  168,  169,  170,  171,  172,  173,  174,
      175,  176,  177,  178,  179,  179,  179,  180,  181,  182,

      183,  184,  185,  186,  187,  188,  189,  191,  192,  193,
      194,  195,  196,  197,  199,  200,  201,  202,  203,  204,
      205,  206,  207,  208,  209,  210,  211,  212,  213,  214,
      214,  215,  216,  218,  218,  219,  219,  220,  221,  222,
      223,  224,  224,  225,  226,  227,  228,  229,  230,  231,
      232,  233,  234,  235,  236,  237,  238,  239,  240,  241,
      242,  243,  244,  245,  247,  248,  249,  251,  252,  253,
      254,  255,  256,  257,  258,  259,  260,  261,  262,  263,
      264,  265,  266,  267,  267,  268,  268,  270,  270,  271,
      272,  273,  274,  275,  276,  276,  277,  278,  279,  280,

      281,  282,  284,  285,  287,  289,  290,  291,  292,  293,
      295,  297,  298,  299,  301,  302,  304,  305,  306,  307,
      308,  309,  310,  311,  312,  313,  314,  315,  316,  318,
      319,  320,  320,  322,  323,  323,  325,  326,  326,  327,
      328,  328,  329,  330,  331,  333,  334,  335,  337,  339,
      340,  341,  342,  343,  345,  346,  347,  348,  349,  351,
      352,  353,  354,  355,  356,  357,  359,  360,  361,  363,
      363,  364,  366,  366,  366,  367,  368,  369,  370,  371,
      372,  373,  375,  377,  379,  380,  381,  383,  385,  387,
      389,  391,  393,  394,  395,  396,  396,  398,  399,  400,

      401,  403,  404,  405,  407,  408,  409,  411,  412,  414,
      416,  418,  420,  422,  423,  425,  425
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   30,
       31,   31,   32,   31,   31,   33,   31,   31,   31,   34,
       31,   31,   31,   31,   35,   31,   31,   36,   31,   31,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   31,   51,   52,   53,   54,
       55,   56,   31,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        6,    6,    7,    7,    6,    6,    1,    1,    1,    1,
        6,    5,    5,    5,    5,    5,    5,    6,    6,    6,
        6,    7,    6,    6,    6,    7,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[324] =
    {   0,
        0,    0,  547,  548,  548,  548,  523,   65,   48,   66,
      507,  548,  548,  521,   62,  548,   63,   61,   72,   89,
       82,  519,  548,   90,  519,   58,  548,    0,   85,  548,
      548,  518,   99,  480,  482,   74,   29,   67,   39,  483,
       51,  482,  490,   88,  471,  480,  478,  483,  548,   69,
      548,  548,  548,  115,  548,    0,  548,  548,  548,  548,
       94,  523,  548,  548,  548,  548,  548,  548,  515,  126,
      548,    0,  548,  146,  151,  170,  188,  148,   81,  514,
      122,  195,  161,  106,  166,  548,  548,  548,  505,  548,
      548,  548,  504,    0,  157,  488,  548,  470,  469,  470,

      463,  475,  462,  477,  464,  470,  456,  457,  454,  454,
      457,  454,  451,    0,  102,  455,  161,  453,  112,  175,
      457,  450,   90,  173,  455,  548,  548,  548,  548,  217,
      548,    0,  220,  240,  548,  225,  243,  111,  548,  471,
      451,    0,  236,  155,  548,  469,  449,  548,  548,  445,
      446,  456,  442,  454,  449,  437,  187,  451,  449,  445,
      437,  443,  446,    0,  432,  436,    0,  437,  434,  424,
      422,  424,  426,  433,  419,  417,  417,  429,  418,  414,
      410,  412,  395,  246,  261,  285,  548,  264,  268,  548,
      548,  272,  277,  274,  300,  223,  286,  548,  392,  387,

      394,    0,  390,    0,    0,  380,  388,  377,  384,    0,
        0,  378,  375,    0,  379,    0,  374,  374,  373,  370,
      382,  370,  374,  377,  376,  374,  364,  369,    0,  357,
      369,  308,  318,  548,  335,  289,  548,  343,  233,  548,
      313,  349,  381,  361,    0,  357,  356,    0,    0,  350,
      351,  354,  341,    0,  341,  324,  331,  326,    0,  333,
      324,  325,  305,  314,  313,    0,  304,  306,    0,  325,
      355,  548,  372,  358,  375,  548,  548,  304,  286,  279,
      257,    0,    0,    0,  254,  245,    0,    0,    0,    0,
        0,    0,  237,  231,  222,  380,  393,  185,  198,  187,

        0,  170,  163,    0,  159,  145,    0,  110,    0,    0,
        0,    0,    0,   87,    0,  548,  445,  452,  455,  462,
      466,  104,  467
    } ;

static yyconst short int yy_def[324] =
    {   0,
      316,    1,  316,  316,  316,  316,  316,  317,  316,  316,
      318,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  319,  319,  316,
      316,  316,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  316,  316,
      316,  316,  316,  317,  316,  317,  316,  316,  316,  316,
      318,  318,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  320,  316,  316,  316,  316,  316,  316,  316,  321,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  319,  317,  318,  316,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  316,  316,  316,  316,  316,
      316,  320,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  322,  321,  316,  316,  316,  316,  316,  316,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  316,  316,  316,  316,  316,  316,  316,
      316,  322,  323,  316,  316,  316,  316,  316,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  316,  316,  316,  316,  323,  316,  316,  316,  316,
      316,  316,  316,  316,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  316,
      316,  316,  316,  316,  316,  316,  316,  319,  319,  319,
      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,  316,  316,  319,  319,  319,

      319,  319,  319,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  319,    0,  316,  316,  316,  316,
      316,  316,  316
    } ;

static yyconst short int yy_nxt[618] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   28,
       28,   28,   29,   28,   28,   28,   30,    4,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   28,   41,
       28,   42,   28,   28,   28,   28,   43,   44,   45,   46,
       47,   48,   28,   28,   28,   49,   50,   51,   52,   55,
       57,   58,   59,   64,  106,   69,   66,   70,   70,   70,
       92,   93,   71,  107,   65,   67,   68,   72,   60,   95,
      111,  126,   96,  112,   73,   87,   74,  114,   82,   82,

       82,  128,   56,   74,  115,   75,   75,   76,  192,   88,
       77,   89,   90,  140,   83,  103,   84,   77,  108,   55,
      109,   78,  104,   79,   80,   98,   99,   77,  105,  110,
      100,   62,  141,   85,   77,  127,  118,  119,  146,  179,
       81,   84,   70,   70,   70,  139,  120,  180,   79,  121,
      315,   80,   56,  166,  130,  131,  139,  147,  131,  173,
      167,   55,  133,  133,  133,   74,  314,   75,   75,   76,
      139,  130,  131,  138,  134,  135,  174,  131,  135,   77,
      138,  139,  139,   78,   74,   79,   76,   76,   76,  145,
      313,  134,  135,  144,   56,  145,   77,  135,   77,  136,

      145,  136,   81,  312,  137,  137,  137,  139,  169,   74,
       79,   82,   82,   82,  145,   77,  175,  144,  170,  171,
      145,  311,  181,   77,  182,  145,  310,   83,  184,   84,
      184,  176,  309,  185,  185,  185,  133,  133,  133,  308,
       77,  137,  137,  137,  206,  207,   85,  307,  186,  187,
      193,  188,  187,  188,   84,  243,  189,  189,  189,  137,
      137,  137,  185,  185,  185,  186,  187,  240,  194,  195,
      196,  187,  190,  306,  244,  190,  305,  185,  185,  185,
      189,  189,  189,  304,  189,  189,  189,  197,  303,  190,
      131,  195,  240,  131,  190,  196,  232,  135,  232,  302,

      135,  233,  233,  233,  234,  235,  239,  131,  240,  237,
      238,  241,  131,  241,  135,  301,  242,  242,  242,  135,
      240,  272,  273,  234,  233,  233,  233,  235,  237,  242,
      242,  242,  238,  240,  233,  233,  233,  239,  300,  299,
      272,  271,  271,  271,  273,  240,  270,  187,  270,  298,
      187,  271,  271,  271,  274,  295,  274,  294,  293,  275,
      275,  275,  292,  291,  187,  242,  242,  242,  290,  187,
      289,  271,  271,  271,  275,  275,  275,  288,  276,  287,
      286,  276,  285,  296,  234,  296,  284,  234,  297,  297,
      297,  275,  275,  275,  283,  276,  297,  297,  297,  282,

      276,  234,  281,  280,  237,  279,  234,  237,  278,  297,
      297,  297,  277,  277,  269,  268,  267,  266,  265,  264,
      263,  237,  272,  262,  261,  272,  237,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  272,
      248,  247,  246,  245,  272,   54,  231,   54,   54,   54,
       54,   54,   61,  230,  229,   61,   61,   61,   61,   94,
       94,   94,  132,  228,  132,  132,  132,  132,  132,  143,
      143,  236,  227,  236,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  205,  204,  203,  202,  201,  200,  199,

      198,  198,  191,  191,  183,  178,  177,  172,  168,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,   62,  149,  148,  142,  129,
       61,  125,  124,  123,  122,  117,  116,  113,  102,  101,
       97,   91,   86,   63,   62,   53,  316,    3,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316
    } ;

static yyconst short int yy_chk[618] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    8,
        9,    9,   10,   15,   37,   18,   17,   18,   18,   18,
       26,   26,   19,   37,   15,   17,   17,   19,   10,   29,
       39,   50,   29,   39,   19,   24,   21,   41,   21,   21,

       21,   61,    8,   20,   41,   20,   20,   20,  322,   24,
       21,   24,   24,   79,   21,   36,   21,   20,   38,   54,
       38,   20,   36,   20,   20,   33,   33,   21,   36,   38,
       33,   61,   79,   21,   20,   50,   44,   44,   84,  123,
       20,   21,   70,   70,   70,  138,   44,  123,   20,   44,
      314,   20,   54,  115,   70,   70,   81,   84,   70,  119,
      115,   95,   74,   74,   74,   75,  308,   75,   75,   75,
      138,   70,   70,   81,   74,   74,  119,   70,   74,   75,
       78,   81,   78,   75,   76,   75,   76,   76,   76,  144,
      306,   74,   74,   83,   95,   83,   75,   74,   76,   77,

       85,   77,   75,  305,   77,   77,   77,   78,  117,   82,
       75,   82,   82,   82,  144,   76,  120,   85,  117,  117,
       83,  303,  124,   82,  124,   85,  302,   82,  130,   82,
      130,  120,  300,  130,  130,  130,  133,  133,  133,  299,
       82,  136,  136,  136,  157,  157,   82,  298,  133,  133,
      143,  134,  133,  134,   82,  196,  134,  134,  134,  137,
      137,  137,  184,  184,  184,  133,  133,  239,  143,  143,
      143,  133,  137,  295,  196,  137,  294,  185,  185,  185,
      188,  188,  188,  293,  189,  189,  189,  143,  286,  137,
      185,  143,  239,  185,  137,  143,  186,  189,  186,  285,

      189,  186,  186,  186,  192,  192,  194,  185,  194,  193,
      193,  195,  185,  195,  189,  281,  195,  195,  195,  189,
      197,  236,  236,  192,  232,  232,  232,  192,  193,  241,
      241,  241,  193,  194,  233,  233,  233,  197,  280,  279,
      236,  270,  270,  270,  236,  197,  235,  233,  235,  278,
      233,  235,  235,  235,  238,  268,  238,  267,  265,  238,
      238,  238,  264,  263,  233,  242,  242,  242,  262,  233,
      261,  271,  271,  271,  274,  274,  274,  260,  242,  258,
      257,  242,  256,  273,  271,  273,  255,  271,  273,  273,
      273,  275,  275,  275,  253,  242,  296,  296,  296,  252,

      242,  271,  251,  250,  275,  247,  271,  275,  246,  297,
      297,  297,  244,  243,  231,  230,  228,  227,  226,  225,
      224,  275,  297,  223,  222,  297,  275,  221,  220,  219,
      218,  217,  215,  213,  212,  209,  208,  207,  206,  297,
      203,  201,  200,  199,  297,  317,  183,  317,  317,  317,
      317,  317,  318,  182,  181,  318,  318,  318,  318,  319,
      319,  319,  320,  180,  320,  320,  320,  320,  320,  321,
      321,  323,  179,  323,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  166,  165,  163,  162,  161,
      160,  159,  158,  156,  155,  154,  153,  152,  151,  150,

      147,  146,  141,  140,  125,  122,  121,  118,  116,  113,
      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  101,  100,   99,   98,   96,   93,   89,   80,   69,
       62,   48,   47,   46,   45,   43,   42,   40,   35,   34,
       32,   25,   22,   14,   11,    7,    3,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[100] =
    {   0,
       23,   24,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   65,
       67,   68,   69,   70,   72,   73,   74,   75,   76,   77,
       80,   82,   83,   84,   85,   86,   87,   88,   89,   90,
       91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
      101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
      111,  112,  113,  114,  115,  116,  117,  118,  119,  120,
      121,  122,  123,  124,  125,  126,  127,  129,  130

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "c.l"
#define INITIAL 0
#line 10 "c.l"
#include <stdio.h>
#include "c.tab.h"

void comment(void);
void count(void);
#line 696 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 "c.l"




#line 863 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 317 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 548 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 100 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 100 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 101 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 23 "c.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "c.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 27 "c.l"
{ count(); return(AUTO); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 28 "c.l"
{ count(); return(BOOL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 29 "c.l"
{ count(); return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 "c.l"
{ count(); return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 31 "c.l"
{ count(); return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 "c.l"
{ count(); return(COMPLEX); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 "c.l"
{ count(); return(CONST); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "c.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "c.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "c.l"
{ count(); return(DO); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "c.l"
{ count(); return(DOUBLE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "c.l"
{ count(); return(ELSE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "c.l"
{ count(); return(ENUM); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 "c.l"
{ count(); return(EXTERN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 "c.l"
{ count(); return(FLOAT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "c.l"
{ count(); return(FOR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "c.l"
{ count(); return(GOTO); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 "c.l"
{ count(); return(IF); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 "c.l"
{ count(); return(IMAGINARY); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 "c.l"
{ count(); return(INLINE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 47 "c.l"
{ count(); return(INT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 48 "c.l"
{ count(); return(LONG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 49 "c.l"
{ count(); return(REGISTER); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 50 "c.l"
{ count(); return(RESTRICT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 51 "c.l"
{ count(); return(RETURN); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 52 "c.l"
{ count(); return(SHORT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 53 "c.l"
{ count(); return(SIGNED); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 54 "c.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 55 "c.l"
{ count(); return(STATIC); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 56 "c.l"
{ count(); return(STRUCT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 57 "c.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 58 "c.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 59 "c.l"
{ count(); return(UNION); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 60 "c.l"
{ count(); return(UNSIGNED); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 61 "c.l"
{ count(); return(VOID); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 62 "c.l"
{ count(); return(VOLATILE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 63 "c.l"
{ count(); return(WHILE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "c.l"
{ count(); return(check_type()); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 67 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 68 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 69 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 70 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "c.l"
{ count(); return(CONSTANT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 "c.l"
{ count(); return(STRING_LITERAL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 82 "c.l"
{ count(); return(ELLIPSIS); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 83 "c.l"
{ count(); return(RIGHT_ASSIGN); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 84 "c.l"
{ count(); return(LEFT_ASSIGN); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 85 "c.l"
{ count(); return(ADD_ASSIGN); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 86 "c.l"
{ count(); return(SUB_ASSIGN); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 87 "c.l"
{ count(); return(MUL_ASSIGN); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 88 "c.l"
{ count(); return(DIV_ASSIGN); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 89 "c.l"
{ count(); return(MOD_ASSIGN); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 90 "c.l"
{ count(); return(AND_ASSIGN); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 91 "c.l"
{ count(); return(XOR_ASSIGN); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 92 "c.l"
{ count(); return(OR_ASSIGN); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 93 "c.l"
{ count(); return(RIGHT_OP); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 94 "c.l"
{ count(); return(LEFT_OP); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 95 "c.l"
{ count(); return(INC_OP); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 96 "c.l"
{ count(); return(DEC_OP); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 97 "c.l"
{ count(); return(PTR_OP); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 98 "c.l"
{ count(); return(AND_OP); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 99 "c.l"
{ count(); return(OR_OP); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 100 "c.l"
{ count(); return(LE_OP); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 101 "c.l"
{ count(); return(GE_OP); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 102 "c.l"
{ count(); return(EQ_OP); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 103 "c.l"
{ count(); return(NE_OP); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 104 "c.l"
{ count(); return(';'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 105 "c.l"
{ count(); return('{'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 106 "c.l"
{ count(); return('}'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 107 "c.l"
{ count(); return(','); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 108 "c.l"
{ count(); return(':'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 109 "c.l"
{ count(); return('='); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 110 "c.l"
{ count(); return('('); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 111 "c.l"
{ count(); return(')'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 112 "c.l"
{ count(); return('['); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 113 "c.l"
{ count(); return(']'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 114 "c.l"
{ count(); return('.'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 115 "c.l"
{ count(); return('&'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 116 "c.l"
{ count(); return('!'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 117 "c.l"
{ count(); return('~'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 118 "c.l"
{ count(); return('-'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 119 "c.l"
{ count(); return('+'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 120 "c.l"
{ count(); return('*'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 121 "c.l"
{ count(); return('/'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 122 "c.l"
{ count(); return('%'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 123 "c.l"
{ count(); return('<'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 124 "c.l"
{ count(); return('>'); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 125 "c.l"
{ count(); return('^'); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 126 "c.l"
{ count(); return('|'); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 127 "c.l"
{ count(); return('?'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 129 "c.l"
{ count(); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 130 "c.l"
{ /* Add code to complain about unmatched characters */ }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 132 "c.l"
ECHO;
	YY_BREAK
#line 1469 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 317 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 317 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 316);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 132 "c.l"


int yywrap(void)
{
	return 1;
}


void comment(void)
{
	char c, prev = 0;
  
	while ((c = input()) != 0)      /* (EOF maps to 0) */
	{
		if (c == '/' && prev == '*')
			return;
		prev = c;
	}
	error("unterminated comment");
}


int column = 0;

void count(void)
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	ECHO;
}


int check_type(void)
{
	return IDENTIFIER;
}
